services:
  - type: web
    name: telegram-gemini-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m app.main
    envVars:
      - key: TG_TOKEN
        sync: false
      - key: REDIS_URL
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: FLASK_SECRET_KEY
        sync: false
      - key: GEMINI_API_KEY_1
        sync: false
      - key: GEMINI_API_KEY_2
        sync: false
      - key: WEBAPP_BASE_URL
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: POLLINATIONS_API_KEY
        sync: false

